sudo: required

language: python
python:
  - "3.8"

env:
  global:
    - OPERATOR_NAME=dash-operator

stages:
  - compile
  - name: push
    if: fork = false

jobs:
  include:
    - stage: compile
      script:
        - make setup/travis image/build TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
    - stage: push
      script:
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
        - export TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
        - docker login --password "$QUAY_PASSWORD" --username "$QUAY_USERNAME" quay.io
        - make setup/travis image/build/push TAG=$TAG
        - docker tag docker.io/armadik/$OPERATOR_NAME:$TAG docker.io/armadik/$OPERATOR_NAME:$BRANCH
        - docker push docker.io/armadik/$OPERATOR_NAME:$BRANCH