sudo: required

language: python
python:
  - "3.8"

env:
  global:
    - OPERATOR_NAME=dash-operator

services:
  - docker

notifications:
  email: false

stages:
  - compile
  - name: push
    if: fork = false

jobs:
  include:
    - stage: compile
      script:
        - make docker-build TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
    - stage: push
      script:
        - export TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker-build TAG=$TAG
        - make docker-push TAG=$TAG
