# permissions for end users to view dashes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dash-viewer-role
rules:
  - apiGroups:
      - demo.my.domain
    resources:
      - dashes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - demo.my.domain
    resources:
      - dashes/status
    verbs:
      - get
