# permissions for end users to edit dashes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dash-editor-role
rules:
- apiGroups:
  - demo.my.domain
  resources:
  - dashes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.my.domain
  resources:
  - dashes/status
  verbs:
  - get
